name: WEBUI/CI_for_WebUI
on:
  workflow_dispatch:
env:
  path_to_project: WEBUI/WEBUI.csproj
  output_path: CMHL.WEBUI
  system_debug: 'false'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    - name: Restore Service
      run: dotnet restore $path_to_project --verbosity "Detailed"

    - name: Build Service
      run: dotnet build $path_to_project --configuration ${{ env.BuildConfiguration }}

    - name: Publish Service
      run: dotnet publish $path_to_project -r linux-x64 --output ${{ runner.temp }}/output_path

    - name: Publish Service
      run: |
        dotnet publish $path_to_project -c Release -o $GITHUB_WORKSPACE 