name: WEBUI/CI_for_WebUI
#on:
  #workflow_dispatch:
on:
  push:
    branches:
      - master
env:
  path_to_project: WEBUI/WEBUI.csproj
  output_path: CMHL.WEBUI
  output_zip: CMHL.WEBUI.zip
  publish_path: $GITHUB_WORKSPACE
  BuildConfiguration: Release
  system_debug: 'false'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    # - name: Restore Service
    #   run: dotnet restore $path_to_project

    # - name: Build Service
    #   run: dotnet build $path_to_project --configuration $BuildConfiguration -r linux-x64

    - name: testing step
      run: |
        echo $GITHUB_WORKSPACE

    # - name: Publish Service
    #   run: |
    #     dotnet publish $path_to_project -r linux-x64 --output $GITHUB_WORKSPACE/$output_path
    #     zip -r $GITHUB_WORKSPACE/$output_zip $GITHUB_WORKSPACE/$output_path

    # - name: Publish Artifact drop
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: drop
    #     path: /home/runner/work/WEBUI/WEBUI/CMHL.WEBUI/$output_zip
    #     if-no-files-found: error
    #     retention-days: 1

