name: WEBUI/CI_for_WebUI
on:
  workflow_dispatch:
env:
  BuildConfiguration: Release
  BuildPlatform: any cpu
  Parameters_RestoreBuildProjects: "**/*.csproj"
  system_debug: 'false'
jobs:
  Job_1:
    name: Agent job 1
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Use .NET Core sdk 5.0.404
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 5.0.404
    - name: Restore WebUI
      run: dotnet restore WEBUI/WEBUI.csproj --verbosity "Detailed"
    - name: Build WebUI
      run: dotnet build WEBUI/WEBUI.csproj --configuration ${{ env.BuildConfiguration }}
    - name: Publish WebUI
      run: dotnet publish ${{ env.Parameters_RestoreBuildProjects }} -r linux-x64 --output ${{ runner.temp }}/WEBUI.csproj
    - name: Publish Artifact
      if: success() || failure()
      uses: actions/upload-artifact@v4.1.0
      with:
        name: drop
        path: "\\\\my\\share\\${{ github.workflow }}\\${{ github.run_number }}"
