name: Test one service one pipeline 

on:
 push:
    paths:
      - 'WEBUI/Controllers/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: echo "Build Success"
