name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'preprod'
        type: choice
        options:
          - preprod
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: echo "Build Success"

  deploy-preprod:
    if: ${{ github.event.inputs.environment == 'preprod' }}
    needs: build
    runs-on: ubuntu-latest
    environment: preprod

    steps:
      - name: Checkout code
        run: echo "Preprod Deployment Done"

  deploy-prod:
    if: ${{ github.event.inputs.environment == 'prod' }}
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
      - name: Checkout code
        run: echo "Prod Deployment Done"
